

export const PRODUCT_ACTION = {
    SET_PRODUCTS:"SET_PRODUCTS",
    FILTER_BY:"FILTER_BY",
    SORT_BY:"SORT_BY"
}

export const CART_ACTION = {
    ADD_TO_CART:"ADD_TO_CART",
    CLEAR_CART_ITEMS:"CLEAR_CART_ITEMS",
    CHECK_CART_ITEM:"CHECK_CART_ITEM",
    GET_CART_ITEMS:"GET_CART_ITEMS"
}